name: ci

on: push

jobs:
  build_docker_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: |
          uname -a
          cat /etc/*release

  use_container:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: |
          uname -a
          cat /etc/*release
